------------------------------------------------------------
-- 1) DROPS SEGUROS
------------------------------------------------------------

-- TABELAS
DROP TABLE T_IMREA_ATENDIMENTO CASCADE CONSTRAINTS;
DROP TABLE T_IMREA_CONSULTA CASCADE CONSTRAINTS;
DROP TABLE T_IMREA_MEDICO CASCADE CONSTRAINTS;
DROP TABLE T_IMREA_PACIENTE CASCADE CONSTRAINTS;
DROP TABLE T_IMREA_ESPECIALIDADE CASCADE CONSTRAINTS;

-- SEQUENCES
DROP SEQUENCE SQ_T_IMREA_ATEND;
DROP SEQUENCE SQ_T_IMREA_CONSULTA;
DROP SEQUENCE SQ_T_IMREA_MEDICO;
DROP SEQUENCE SQ_T_IMREA_PACIENTE;
DROP SEQUENCE SQ_T_IMREA_ESPECIALIDADE;

------------------------------------------------------------
-- 2) TABELAS
------------------------------------------------------------

CREATE TABLE T_IMREA_PACIENTE (
  ID_PACIENTE    NUMBER         PRIMARY KEY,
  NM_PACIENTE    VARCHAR2(100)  NOT NULL,
  DT_NASCIMENTO  DATE,
  NR_CPF         VARCHAR2(11)   UNIQUE,
  DS_EMAIL       VARCHAR2(120)
);

CREATE TABLE T_IMREA_ESPECIALIDADE (
  ID_ESPECIALIDADE  NUMBER        PRIMARY KEY,
  NM_ESPECIALIDADE  VARCHAR2(60)  NOT NULL
);

CREATE TABLE T_IMREA_MEDICO (
  ID_MEDICO         NUMBER         PRIMARY KEY,
  NM_MEDICO         VARCHAR2(100)  NOT NULL,
  NR_CRM            VARCHAR2(30)   UNIQUE,
  ID_ESPECIALIDADE  NUMBER         REFERENCES T_IMREA_ESPECIALIDADE(ID_ESPECIALIDADE)
);


CREATE TABLE T_IMREA_CONSULTA (
  ID_CONSULTA    NUMBER         PRIMARY KEY,
  ID_PACIENTE    NUMBER         NOT NULL REFERENCES T_IMREA_PACIENTE(ID_PACIENTE),
  ID_MEDICO      NUMBER         NOT NULL REFERENCES T_IMREA_MEDICO(ID_MEDICO),
  DT_INICIO      TIMESTAMP      NOT NULL,
  DT_FIM         TIMESTAMP      NOT NULL,
  DS_STATUS      VARCHAR2(20)   DEFAULT 'AGENDADA',
  TP_MODALIDADE  VARCHAR2(12)   DEFAULT 'TELE' NOT NULL,
  DS_LINK        VARCHAR2(255),
  DS_PLATAFORMA  VARCHAR2(60)   DEFAULT 'IMREA' NOT NULL,
  CONSTRAINT CK_IMREA_CONSULTA_MODALIDADE CHECK (TP_MODALIDADE = 'TELE')
);

CREATE TABLE T_IMREA_ATENDIMENTO (
  ID_ATENDIMENTO      NUMBER        PRIMARY KEY,
  ID_CONSULTA         NUMBER        NOT NULL REFERENCES T_IMREA_CONSULTA(ID_CONSULTA),
  NR_GRAVIDADE        NUMBER(1)     CHECK (NR_GRAVIDADE BETWEEN 1 AND 5),
  DT_ABERTURA         TIMESTAMP     NOT NULL,
  DT_ENCERRAMENTO     TIMESTAMP,
  NR_PRIORIDADE_CALC  NUMBER(10,2)
);

------------------------------------------------------------
-- 3) REGRAS / ÍNDICES
------------------------------------------------------------


ALTER TABLE T_IMREA_CONSULTA
  ADD CONSTRAINT UQ_CONSULTA_MEDICO_INICIO UNIQUE (ID_MEDICO, DT_INICIO);


ALTER TABLE T_IMREA_CONSULTA
  ADD CONSTRAINT UQ_CONSULTA_PACIENTE_INICIO UNIQUE (ID_PACIENTE, DT_INICIO);


CREATE INDEX IX_CONSULTA_MEDICO_PERIODO
  ON T_IMREA_CONSULTA (ID_MEDICO, DT_INICIO, DT_FIM);

------------------------------------------------------------
-- 4) SEQUENCES
------------------------------------------------------------

CREATE SEQUENCE SQ_T_IMREA_PACIENTE      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_IMREA_ESPECIALIDADE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_IMREA_MEDICO        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_IMREA_CONSULTA      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_IMREA_ATEND         START WITH 1 INCREMENT BY 1 NOCACHE;

------------------------------------------------------------
-- 5) COMMIT FINAL
------------------------------------------------------------
COMMIT;





